# Generated by Django 6.0.3 on 2026-04-05 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_currency_date_alter_currency_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currency",
            name="date",
        ),
        migrations.AddField(
            model_name="currency",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
